// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('testing falabella', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('testing falabella', async function() {
    // Test name: testing falabella
    // Step # | name | target | value
    // 1 | open | /falabella-cl/ | 
    await driver.get("https://www.falabella.com/falabella-cl/")
    // 2 | setWindowSize | 1280x674 | 
    await driver.manage().window().setRect(1280, 674)
    // 3 | mouseOver | css=#showcase-Showcase-08181ade-7cbe-465c-9905-2797a7aa47f1-item-1 .BackgroundImageOnly-module_half-width-only-desktop__1bG9y:nth-child(1) | 
    {
      const element = await driver.findElement(By.css("#showcase-Showcase-08181ade-7cbe-465c-9905-2797a7aa47f1-item-1 .BackgroundImageOnly-module_half-width-only-desktop__1bG9y:nth-child(1)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 4 | mouseOut | css=#showcase-Showcase-08181ade-7cbe-465c-9905-2797a7aa47f1-item-1 .BackgroundImageOnly-module_half-width-only-desktop__1bG9y:nth-child(1) | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 5 | runScript | window.scrollTo(0,658) | 
    await driver.executeScript("window.scrollTo(0,658)")
    // 6 | runScript | window.scrollTo(0,894) | 
    await driver.executeScript("window.scrollTo(0,894)")
    // 7 | runScript | window.scrollTo(0,45.33333206176758) | 
    await driver.executeScript("window.scrollTo(0,45.33333206176758)")
    // 8 | click | css=.Header-module_menuBox__3kMK7 > #header-med-categories-menu-CategoryMenu-1df0cec7-821b-4456-ad50-2c712dfbd7b4 .CategoryMenuButton-module_hamburger-line__3LiSs | 
    await driver.findElement(By.css(".Header-module_menuBox__3kMK7 > #header-med-categories-menu-CategoryMenu-1df0cec7-821b-4456-ad50-2c712dfbd7b4 .CategoryMenuButton-module_hamburger-line__3LiSs")).click()
    // 9 | click | css=.FirstLevelItems_menuText-2 | 
    await driver.findElement(By.css(".FirstLevelItems_menuText-2")).click()
    // 10 | click | linkText=Smartphones | 
    await driver.findElement(By.linkText("Smartphones")).click()
    // 11 | mouseOver | id=testId-Pod-action-prod22263309 | 
    {
      const element = await driver.findElement(By.id("testId-Pod-action-prod22263309"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 12 | mouseOut | id=testId-Pod-action-prod22263309 | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 13 | click | css=#testId-Pod-action-prod22263309 > .jsx-3488318063 > .jsx-3488318063 | 
    await driver.findElement(By.css("#testId-Pod-action-prod22263309 > .jsx-3488318063 > .jsx-3488318063")).click()
    // 14 | mouseOver | css=.jsx-1816208196 | 
    {
      const element = await driver.findElement(By.css(".jsx-1816208196"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 15 | click | css=.jsx-1816208196 | 
    await driver.findElement(By.css(".jsx-1816208196")).click()
    // 16 | mouseOut | css=.button-primary-xtra-large | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 17 | runScript | window.scrollTo(0,345.3333435058594) | 
    await driver.executeScript("window.scrollTo(0,345.3333435058594)")
    // 18 | mouseOver | id=testId-Operator-Liberado | 
    {
      const element = await driver.findElement(By.id("testId-Operator-Liberado"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 19 | click | id=testId-Operator-Liberado | 
    await driver.findElement(By.id("testId-Operator-Liberado")).click()
    // 20 | mouseOut | id=testId-Operator-Liberado | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 21 | mouseOver | css=.button-primary-medium | 
    {
      const element = await driver.findElement(By.css(".button-primary-medium"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 22 | click | css=.button-primary-medium | 
    await driver.findElement(By.css(".button-primary-medium")).click()
    // 23 | mouseOver | css=.button-secondary-link | 
    {
      const element = await driver.findElement(By.css(".button-secondary-link"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 24 | click | css=.button-secondary-link | 
    await driver.findElement(By.css(".button-secondary-link")).click()
    // 25 | runScript | window.scrollTo(0,340) | 
    await driver.executeScript("window.scrollTo(0,340)")
    // 26 | close |  | 
    await driver.close()
  })
})
